name: .NET Core

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'  # Specify the .NET version you want to use

    - name: Install dependencies
      run: dotnet restore src/Meme.Domain/Meme.Domain.sln

    - name: Build
      run: dotnet build src/Meme.Domain/Meme.Domain.sln --configuration Release --no-restore

    - name: Pack
      run: dotnet pack src/Meme.Domain/Meme.Domain.sln --configuration Release --output nupkg
