name: .NET Core

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'  # Specify the .NET version you want to use.

    - name: Install dependencies
      run: dotnet restore src/Meme.Domain/Meme.Domain.sln

    - name: Build
      run: dotnet build src/Meme.Domain/Meme.Domain.sln --configuration Release --no-restore

    - name: 'Get Version'
      id: version
      uses: battila7/get-version-action@v2
      
    - name: Pack
      run: dotnet pack src/Meme.Domain/Meme.Domain.sln --configuration Release --include-symbols -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --output nupkg    

    - name: Add github as source
      run: dotnet nuget add source --username isboat --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/isboat/index.json"
      
    - name: Publish to GitHub Packages 
      run: dotnet nuget push nupkg/*.nupkg --source "github" --api-key ${{ secrets.MYPAT }} 
