name: .NET Core

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'  # Specify the .NET version you want to use

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build src/Meme.Domain/Meme.Domain.sln --configuration Release --no-restore

    - name: Pack
      run: dotnet pack src/Meme.Domain/Meme.Domain.sln --configuration Release --output nupkg

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git commit -m "Automated build and package"

    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: git push origin main
